### ISSUE TITLE
Work with JavaScript?

### ISSUE THREAD

**Issue by curran** [replit/Codemirror-CSS-color-picker#7]
Greetings,

I was hoping this would work with color strings defined in JS code, like this:

```
const color = '#FFFFFF';
```

However when I tried it, it did not.

Is the library only intended for use in CSS code? Or would it be possible to make it work for hex colors in other language contexts as well, such as JS or HTML? Thanks!

**Comment by sergeichestakov** [comment]
Hey @curran! Thanks for the report, that's a great point. In theory, this should work with any language but at the moment it's only guaranteed to work with CSS.

My guess would be when you tried using the extension in JS or another language it doesn't work because the grammar doesn't correctly identify the strings as CSS expressions. e.g. https://github.com/replit/Codemirror-CSS-color-picker/blob/5971e1152468eb4ecef043e8ee35e15ba12a3677/src/index.ts#L42

It's possible that the JS grammar is less specific than the CSS grammar in that front so our logic doesn't catch it when we parse the syntax tree for strings with CSS values. @masad-frost do you know what it would take to make this work and if we want to support other languages?

**Comment by curran** [comment]
Oh nice! Thank you so much for investigating. I'd guess what we need to do is

 * figure out what `type.name` is for strings in JavaScript, then
 * use regex (or something else) to check for color syntax.

I'd be happy if it only supports hex strings of the form `#FFFFFF`.

**Comment by curran** [comment]
Whoah look at what GitHub does! `#FF0000` `#00FF00` `#0000FF`

**Comment by masad-frost** [comment]
We would have to switch from using the syntax tree to using regex matching. Feel free to open a PR that conditionally allows using regex instead of the AST. Or fork off if it's easier

**Comment by curran** [comment]
Can we reopen this? It seems doable.

**Comment by curran** [comment]
I think we could pull some ideas from here re: the regex approach https://github.com/replit/codemirror-interact/blob/master/src/interact.ts#L145

**Comment by masad-frost** [comment]
> Can we reopen this? It seems doable.

As mentioned, definitely doable, but out of scope for this repo. I think it's an entirely different plugin you're looking for that needs to be built separately.

**Comment by curran** [comment]
Ok, if the scope of this extension is to support strictly CSS only, then I guess that makes sense.

I came across another extension that might work https://github.com/uiwjs/react-codemirror/tree/master/extensions/color
